import "server-only";

/*
 * Instaladores de duplo clique — o que elimina o terminal da vida do cliente.
 *
 * O passo "abra o terminal DENTRO da pasta" era onde a instalação morria: quem
 * não é técnico não sabe fazer isso, e explicar por escrito não resolve (muda
 * de Windows para Mac, e no Windows mudou entre versões). Estes arquivos
 * resolvem sozinhos: `%~dp0` (Windows) e `dirname "$0"` (Mac/Linux) dão a
 * pasta do próprio script, então ele entra no lugar certo independente de onde
 * o cliente descompactou — Área de Trabalho, Downloads, tanto faz.
 *
 * Os .bat vão SEM ACENTO de propósito: o console do Windows ainda erra
 * acentuação dependendo da região, e "InstalaÃ§Ã£o" na tela assusta mais do
 * que texto simples.
 *
 * Node ausente não vira beco sem saída: no Windows tentamos instalar pelo
 * winget (já vem no Windows 10/11) e, sem ele, abrimos o site sozinho.
 */

const crlf = (linhas: string[]) => linhas.join("\r\n");

/*
 * PASTA SINCRONIZADA NA NUVEM: a falha real que derrubou a primeira
 * instalação.
 *
 * O cliente descompactou em G:\Outros computadores\...\Backup Dropbox\ — uma
 * pasta do Google Drive. Instalar node_modules ali não funciona: são milhares
 * de arquivinhos, e o sincronizador abre/trava/copia cada um enquanto o npm
 * ainda está escrevendo. O resultado é uma enxurrada de TAR_ENTRY_ERROR,
 * EPERM ao limpar e, no fim, "Invalid package config" — um pacote pela metade.
 *
 * Nenhuma mensagem dessas diz "sua pasta está na nuvem", então o cliente não
 * tem como adivinhar. O instalador passa a resolver sozinho: detecta o caso,
 * copia tudo para uma pasta local de verdade e instala lá. E, se a detecção
 * falhar, a instalação que der errado é REFEITA na pasta local antes de
 * desistir — a rede de segurança pega até antivírus e drive de rede.
 */
export const INSTALAR_BAT = crlf([
  "@echo off",
  "chcp 65001 >nul",
  "title PaginaPro - Instalar o agente",
  "setlocal",
  "",
  'set "RAIZ=%~dp0"',
  'set "RAIZ=%RAIZ:~0,-1%"',
  'set "DESTINO=%LOCALAPPDATA%\\PaginaPro-Agente"',
  'set "PASTA=%RAIZ%"',
  'set "MOVEU=0"',
  "",
  "echo.",
  "echo   ============================================",
  "echo     PAGINAPRO - INSTALACAO DO AGENTE",
  "echo   ============================================",
  "echo.",
  "echo   Isto leva alguns minutos. Pode deixar rodando.",
  "echo.",
  "",
  'if not exist "%RAIZ%\\agente\\package.json" goto ERRO_PASTA',
  "",
  "where node >nul 2>nul",
  "if errorlevel 1 goto SEM_NODE",
  "",
  "rem --- a pasta esta dentro de um servico de nuvem? ---",
  'set "NUVEM="',
  'echo "%RAIZ%" | findstr /i /c:"onedrive" /c:"dropbox" /c:"google drive" /c:"googledrive" /c:"outros computadores" /c:"meu drive" /c:"my drive" /c:"icloud" /c:"sincroniz" >nul && set "NUVEM=1"',
  'if "%RAIZ:~0,2%"=="\\\\" set "NUVEM=1"',
  'if defined NUVEM goto MOVER',
  "goto INSTALAR",
  "",
  ":MOVER",
  "echo   ATENCAO: esta pasta fica dentro de um servico de nuvem",
  "echo   (Google Drive, OneDrive, Dropbox) ou num drive de rede.",
  "echo   A instalacao falha nesses lugares, porque a nuvem mexe nos",
  "echo   arquivos enquanto eles estao sendo criados.",
  "echo.",
  "echo   Sem problema: vou instalar numa pasta local do seu",
  "echo   computador. Voce continua usando este mesmo atalho.",
  "echo.",
  "call :COPIAR",
  "if errorlevel 1 goto ERRO_COPIA",
  'set "PASTA=%DESTINO%"',
  'set "MOVEU=1"',
  "",
  ":INSTALAR",
  'cd /d "%PASTA%\\agente" || goto ERRO',
  "echo   [1 de 2] Baixando os componentes do agente...",
  "echo.",
  "call npm install --no-audit --no-fund",
  "if errorlevel 1 goto FALHOU",
  "",
  "echo.",
  "echo   [2 de 2] Instalando o navegador que o agente usa...",
  "echo.",
  "call npx --yes playwright install chromium",
  "if errorlevel 1 goto FALHOU",
  "",
  "echo.",
  "echo   ============================================",
  "echo     PRONTO! Instalacao concluida.",
  "echo.",
  'if "%MOVEU%"=="1" echo     Instalado em: %PASTA%',
  'if "%MOVEU%"=="1" echo.',
  "echo     Agora feche esta janela e clique duas vezes",
  "echo     em LIGAR-AGENTE para comecar a usar.",
  "echo   ============================================",
  "echo.",
  "pause",
  "exit /b 0",
  "",
  ":FALHOU",
  'if "%MOVEU%"=="1" goto ERRO',
  "echo.",
  "echo   ============================================",
  "echo   A instalacao nao funcionou nesta pasta.",
  "echo   Vou tentar de novo numa pasta local do seu",
  "echo   computador. Aguarde.",
  "echo   ============================================",
  "echo.",
  "call :COPIAR",
  "if errorlevel 1 goto ERRO_COPIA",
  'set "PASTA=%DESTINO%"',
  'set "MOVEU=1"',
  "goto INSTALAR",
  "",
  ":COPIAR",
  'if not exist "%DESTINO%" mkdir "%DESTINO%" >nul 2>nul',
  "rem node_modules fica de fora: pode ter sobrado quebrado da tentativa anterior.",
  'robocopy "%RAIZ%" "%DESTINO%" /E /XD node_modules /NFL /NDL /NJH /NJS /nc /ns /np >nul',
  "if errorlevel 8 exit /b 1",
  "exit /b 0",
  "",
  ":ERRO_COPIA",
  "echo.",
  "echo   Nao consegui criar a pasta local.",
  "echo   Solucao manual: mova a pasta paginapro-agente para a sua",
  "echo   Area de Trabalho e clique em INSTALAR-AGENTE de novo.",
  "echo.",
  "pause",
  "exit /b 1",
  "",
  ":SEM_NODE",
  "echo   O Node ainda nao esta neste computador.",
  "echo   Ele e gratuito e o agente precisa dele para funcionar.",
  "echo.",
  "where winget >nul 2>nul",
  "if errorlevel 1 goto ABRIR_SITE",
  'choice /c SN /n /m "  Posso instalar o Node agora, automaticamente? [S/N]: "',
  "if errorlevel 2 goto ABRIR_SITE",
  "echo.",
  "echo   Instalando o Node. Se aparecer uma janela pedindo permissao, aceite.",
  "echo.",
  "winget install --id OpenJS.NodeJS.LTS -e --accept-source-agreements --accept-package-agreements",
  "echo.",
  "echo   ============================================",
  "echo     Node instalado!",
  "echo.",
  "echo     FECHE esta janela e clique duas vezes em",
  "echo     INSTALAR-AGENTE outra vez para continuar.",
  "echo   ============================================",
  "echo.",
  "pause",
  "exit /b 0",
  "",
  ":ABRIR_SITE",
  "echo.",
  "echo   Vou abrir o site do Node no seu navegador.",
  "echo   Baixe a versao LTS, instale, e depois clique",
  "echo   duas vezes em INSTALAR-AGENTE outra vez.",
  "echo.",
  "start https://nodejs.org/en/download",
  "pause",
  "exit /b 1",
  "",
  ":ERRO_PASTA",
  "echo   Nao encontrei a pasta 'agente'.",
  "echo   Descompacte o arquivo .zip inteiro antes de clicar aqui.",
  "echo   (No Windows: botao direito no .zip, 'Extrair tudo')",
  "pause",
  "exit /b 1",
  "",
  ":ERRO",
  "echo.",
  "echo   Algo deu errado na instalacao, mesmo na pasta local.",
  "echo.",
  "echo   O que costuma resolver:",
  "echo     1. Desligue o antivirus por alguns minutos e tente de novo;",
  "echo     2. Confira se o computador tem espaco em disco;",
  "echo     3. Confira a internet.",
  "echo.",
  "echo   Se continuar, tire um print desta janela inteira e mande",
  "echo   para o suporte.",
  "echo.",
  "pause",
  "exit /b 1",
  "",
]);

export const LIGAR_BAT = crlf([
  "@echo off",
  "chcp 65001 >nul",
  "title PaginaPro - Agente LIGADO (nao feche)",
  "setlocal",
  "",
  'set "RAIZ=%~dp0"',
  'set "RAIZ=%RAIZ:~0,-1%"',
  'set "DESTINO=%LOCALAPPDATA%\\PaginaPro-Agente"',
  "",
  "rem A instalacao pode ter ido para a pasta local (quando esta aqui fica",
  "rem dentro do Google Drive/OneDrive/Dropbox). Procura nos dois lugares,",
  "rem para o cliente continuar clicando sempre neste mesmo atalho.",
  'set "PASTA="',
  'if exist "%RAIZ%\\agente\\node_modules" set "PASTA=%RAIZ%"',
  'if not defined PASTA if exist "%DESTINO%\\agente\\node_modules" set "PASTA=%DESTINO%"',
  "if not defined PASTA goto FALTA_INSTALAR",
  "",
  "where node >nul 2>nul",
  "if errorlevel 1 goto FALTA_INSTALAR",
  'cd /d "%PASTA%\\agente" || goto ERRO_PASTA',
  "",
  "echo.",
  "echo   ============================================",
  "echo     AGENTE LIGADO",
  "echo.",
  "echo     NAO FECHE esta janela enquanto estiver",
  "echo     usando a prospeccao. Para desligar, e so",
  "echo     fechar a janela.",
  "echo   ============================================",
  "echo.",
  "call npm run servico",
  "echo.",
  "echo   O agente parou. Feche esta janela ou clique",
  "echo   em LIGAR-AGENTE de novo para religar.",
  "pause",
  "exit /b 0",
  "",
  ":FALTA_INSTALAR",
  "echo.",
  "echo   Ainda falta instalar.",
  "echo   Clique duas vezes em INSTALAR-AGENTE primeiro.",
  "echo.",
  "pause",
  "exit /b 1",
  "",
  ":ERRO_PASTA",
  "echo   Nao encontrei a pasta 'agente'.",
  "echo   Descompacte o arquivo .zip inteiro antes de clicar aqui.",
  "pause",
  "exit /b 1",
  "",
]);

/*
 * Mac e Linux. A extensão .command é o que faz o Finder abrir com dois
 * cliques; o arquivo precisa sair do .zip já executável (veja unixPermissions
 * na rota de download), senão o duplo clique não faz nada.
 */
export const INSTALAR_COMMAND = [
  "#!/bin/bash",
  'RAIZ="$(cd "$(dirname "$0")" && pwd)"',
  'DESTINO="$HOME/PaginaPro-Agente"',
  'PASTA="$RAIZ"',
  "MOVEU=0",
  "",
  '[ -f "$RAIZ/agente/package.json" ] || { echo "Nao encontrei a pasta agente. Descompacte o .zip inteiro."; read -r; exit 1; }',
  "",
  "echo",
  'echo "  ============================================"',
  'echo "    PAGINAPRO - INSTALACAO DO AGENTE"',
  'echo "  ============================================"',
  "echo",
  "",
  "# iCloud, Dropbox e Google Drive quebram a instalacao do mesmo jeito que no",
  "# Windows: sincronizam os arquivos enquanto o npm ainda esta escrevendo.",
  'case "$RAIZ" in',
  "  *Mobile\\ Documents*|*Dropbox*|*Google\\ Drive*|*OneDrive*|*CloudStorage*)",
  '    echo "  ATENCAO: esta pasta fica dentro de um servico de nuvem."',
  '    echo "  A instalacao falha ali. Vou instalar em: $DESTINO"',
  "    echo",
  '    mkdir -p "$DESTINO"',
  '    rsync -a --exclude node_modules "$RAIZ/" "$DESTINO/" 2>/dev/null || cp -R "$RAIZ/." "$DESTINO/"',
  '    PASTA="$DESTINO"',
  "    MOVEU=1",
  "    ;;",
  "esac",
  "",
  'cd "$PASTA/agente" || { echo "  Nao consegui entrar na pasta."; read -r; exit 1; }',
  "",
  "if ! command -v node >/dev/null 2>&1; then",
  '  echo "  O Node ainda nao esta neste computador."',
  '  echo "  Ele e gratuito e o agente precisa dele."',
  "  echo",
  "  if command -v brew >/dev/null 2>&1; then",
  '    read -r -p "  Posso instalar agora com o Homebrew? [s/N] " r',
  '    if [ "$r" = "s" ] || [ "$r" = "S" ]; then',
  "      brew install node",
  "    else",
  '      open "https://nodejs.org/en/download" 2>/dev/null || xdg-open "https://nodejs.org/en/download"',
  '      echo "  Instale o Node e clique aqui de novo."; read -r; exit 1',
  "    fi",
  "  else",
  '    echo "  Vou abrir o site do Node. Instale a versao LTS e clique aqui de novo."',
  '    open "https://nodejs.org/en/download" 2>/dev/null || xdg-open "https://nodejs.org/en/download"',
  "    read -r; exit 1",
  "  fi",
  "fi",
  "",
  "instalar() {",
  '  echo "  [1 de 2] Baixando os componentes do agente..."',
  "  npm install --no-audit --no-fund || return 1",
  "  echo",
  '  echo "  [2 de 2] Instalando o navegador que o agente usa..."',
  "  npx --yes playwright install chromium || return 1",
  "  return 0",
  "}",
  "",
  "if ! instalar; then",
  "  # Rede de segurança: falhou aqui, refaz na pasta local antes de desistir.",
  '  if [ "$MOVEU" = "0" ]; then',
  "    echo",
  '    echo "  Nao funcionou nesta pasta. Tentando numa pasta local..."',
  "    echo",
  '    mkdir -p "$DESTINO"',
  '    rsync -a --exclude node_modules "$RAIZ/" "$DESTINO/" 2>/dev/null || cp -R "$RAIZ/." "$DESTINO/"',
  '    cd "$DESTINO/agente" || { read -r; exit 1; }',
  "    MOVEU=1",
  '    instalar || { echo; echo "  Algo deu errado. Mande um print desta janela para o suporte."; read -r; exit 1; }',
  "  else",
  "    echo",
  '    echo "  Algo deu errado. Mande um print desta janela para o suporte."',
  "    read -r; exit 1",
  "  fi",
  "fi",
  "",
  "echo",
  'echo "  ============================================"',
  'echo "    PRONTO!"',
  '[ "$MOVEU" = "1" ] && echo "    Instalado em: $DESTINO" && echo',
  'echo "    Feche esta janela e abra o LIGAR-AGENTE.command"',
  'echo "  ============================================"',
  "echo",
  'read -r -p "  Aperte Enter para fechar."',
  "",
].join("\n");

export const LIGAR_COMMAND = [
  "#!/bin/bash",
  'RAIZ="$(cd "$(dirname "$0")" && pwd)"',
  'DESTINO="$HOME/PaginaPro-Agente"',
  "",
  "# A instalacao pode ter ido para a pasta local (nuvem). Procura nos dois.",
  'if [ -d "$RAIZ/agente/node_modules" ]; then',
  '  PASTA="$RAIZ"',
  'elif [ -d "$DESTINO/agente/node_modules" ]; then',
  '  PASTA="$DESTINO"',
  "else",
  '  echo "  Ainda falta instalar. Abra o INSTALAR-AGENTE.command primeiro."',
  "  read -r; exit 1",
  "fi",
  "",
  'cd "$PASTA/agente" || { echo "  Nao encontrei a pasta agente."; read -r; exit 1; }',
  "",
  "if ! command -v node >/dev/null 2>&1; then",
  '  echo "  Ainda falta instalar. Abra o INSTALAR-AGENTE.command primeiro."',
  "  read -r; exit 1",
  "fi",
  "",
  "echo",
  'echo "  ============================================"',
  'echo "    AGENTE LIGADO"',
  "echo",
  'echo "    NAO FECHE esta janela enquanto estiver"',
  'echo "    usando a prospeccao."',
  'echo "  ============================================"',
  "echo",
  "npm run servico",
  "echo",
  'read -r -p "  O agente parou. Aperte Enter para fechar."',
  "",
].join("\n");
