import "server-only";

/*
 * Instaladores de duplo clique — o que elimina o terminal da vida do cliente.
 *
 * O passo "abra o terminal DENTRO da pasta" era onde a instalação morria: quem
 * não é técnico não sabe fazer isso, e explicar por escrito não resolve (muda
 * de Windows para Mac, e no Windows mudou entre versões). Estes arquivos
 * resolvem sozinhos: `%~dp0` (Windows) e `dirname "$0"` (Mac/Linux) dão a
 * pasta do próprio script, então ele entra no lugar certo independente de onde
 * o cliente descompactou — Área de Trabalho, Downloads, tanto faz.
 *
 * Os .bat vão SEM ACENTO de propósito: o console do Windows ainda erra
 * acentuação dependendo da região, e "InstalaÃ§Ã£o" na tela assusta mais do
 * que texto simples.
 *
 * Node ausente não vira beco sem saída: no Windows tentamos instalar pelo
 * winget (já vem no Windows 10/11) e, sem ele, abrimos o site sozinho.
 */

const crlf = (linhas: string[]) => linhas.join("\r\n");

export const INSTALAR_BAT = crlf([
  "@echo off",
  "chcp 65001 >nul",
  "title PaginaPro - Instalar o agente",
  "setlocal",
  "",
  "echo.",
  "echo   ============================================",
  "echo     PAGINAPRO - INSTALACAO DO AGENTE",
  "echo   ============================================",
  "echo.",
  "echo   Isto leva alguns minutos. Pode deixar rodando.",
  "echo.",
  "",
  'cd /d "%~dp0agente" || goto ERRO_PASTA',
  "",
  "where node >nul 2>nul",
  "if errorlevel 1 goto SEM_NODE",
  "",
  "echo   [1 de 2] Baixando os componentes do agente...",
  "echo.",
  "call npm install",
  "if errorlevel 1 goto ERRO",
  "",
  "echo.",
  "echo   [2 de 2] Instalando o navegador que o agente usa...",
  "echo.",
  "call npx --yes playwright install chromium",
  "if errorlevel 1 goto ERRO",
  "",
  "echo.",
  "echo   ============================================",
  "echo     PRONTO! Instalacao concluida.",
  "echo.",
  "echo     Agora feche esta janela e clique duas vezes",
  "echo     em LIGAR-AGENTE para comecar a usar.",
  "echo   ============================================",
  "echo.",
  "pause",
  "exit /b 0",
  "",
  ":SEM_NODE",
  "echo   O Node ainda nao esta neste computador.",
  "echo   Ele e gratuito e o agente precisa dele para funcionar.",
  "echo.",
  "where winget >nul 2>nul",
  "if errorlevel 1 goto ABRIR_SITE",
  'choice /c SN /n /m "  Posso instalar o Node agora, automaticamente? [S/N]: "',
  "if errorlevel 2 goto ABRIR_SITE",
  "echo.",
  "echo   Instalando o Node. Se aparecer uma janela pedindo permissao, aceite.",
  "echo.",
  "winget install --id OpenJS.NodeJS.LTS -e --accept-source-agreements --accept-package-agreements",
  "echo.",
  "echo   ============================================",
  "echo     Node instalado!",
  "echo.",
  "echo     FECHE esta janela e clique duas vezes em",
  "echo     INSTALAR-AGENTE outra vez para continuar.",
  "echo   ============================================",
  "echo.",
  "pause",
  "exit /b 0",
  "",
  ":ABRIR_SITE",
  "echo.",
  "echo   Vou abrir o site do Node no seu navegador.",
  "echo   Baixe a versao LTS, instale, e depois clique",
  "echo   duas vezes em INSTALAR-AGENTE outra vez.",
  "echo.",
  "start https://nodejs.org/en/download",
  "pause",
  "exit /b 1",
  "",
  ":ERRO_PASTA",
  "echo   Nao encontrei a pasta 'agente'.",
  "echo   Descompacte o arquivo .zip inteiro antes de clicar aqui.",
  "echo   (No Windows: botao direito no .zip, 'Extrair tudo')",
  "pause",
  "exit /b 1",
  "",
  ":ERRO",
  "echo.",
  "echo   Algo deu errado na instalacao.",
  "echo   Tire um print desta janela inteira e mande para o suporte.",
  "echo.",
  "pause",
  "exit /b 1",
  "",
]);

export const LIGAR_BAT = crlf([
  "@echo off",
  "chcp 65001 >nul",
  "title PaginaPro - Agente LIGADO (nao feche)",
  "setlocal",
  "",
  'cd /d "%~dp0agente" || goto ERRO_PASTA',
  "",
  "where node >nul 2>nul",
  "if errorlevel 1 goto FALTA_INSTALAR",
  'if not exist "node_modules" goto FALTA_INSTALAR',
  "",
  "echo.",
  "echo   ============================================",
  "echo     AGENTE LIGADO",
  "echo.",
  "echo     NAO FECHE esta janela enquanto estiver",
  "echo     usando a prospeccao. Para desligar, e so",
  "echo     fechar a janela.",
  "echo   ============================================",
  "echo.",
  "call npm run servico",
  "echo.",
  "echo   O agente parou. Feche esta janela ou clique",
  "echo   em LIGAR-AGENTE de novo para religar.",
  "pause",
  "exit /b 0",
  "",
  ":FALTA_INSTALAR",
  "echo.",
  "echo   Ainda falta instalar.",
  "echo   Clique duas vezes em INSTALAR-AGENTE primeiro.",
  "echo.",
  "pause",
  "exit /b 1",
  "",
  ":ERRO_PASTA",
  "echo   Nao encontrei a pasta 'agente'.",
  "echo   Descompacte o arquivo .zip inteiro antes de clicar aqui.",
  "pause",
  "exit /b 1",
  "",
]);

/*
 * Mac e Linux. A extensão .command é o que faz o Finder abrir com dois
 * cliques; o arquivo precisa sair do .zip já executável (veja unixPermissions
 * na rota de download), senão o duplo clique não faz nada.
 */
export const INSTALAR_COMMAND = [
  "#!/bin/bash",
  'cd "$(dirname "$0")/agente" || { echo "Nao encontrei a pasta agente. Descompacte o .zip inteiro."; read -r; exit 1; }',
  "",
  "echo",
  'echo "  ============================================"',
  'echo "    PAGINAPRO - INSTALACAO DO AGENTE"',
  'echo "  ============================================"',
  "echo",
  "",
  "if ! command -v node >/dev/null 2>&1; then",
  '  echo "  O Node ainda nao esta neste computador."',
  '  echo "  Ele e gratuito e o agente precisa dele."',
  "  echo",
  "  if command -v brew >/dev/null 2>&1; then",
  '    read -r -p "  Posso instalar agora com o Homebrew? [s/N] " r',
  '    if [ "$r" = "s" ] || [ "$r" = "S" ]; then',
  "      brew install node",
  "    else",
  '      open "https://nodejs.org/en/download" 2>/dev/null || xdg-open "https://nodejs.org/en/download"',
  '      echo "  Instale o Node e clique aqui de novo."; read -r; exit 1',
  "    fi",
  "  else",
  '    echo "  Vou abrir o site do Node. Instale a versao LTS e clique aqui de novo."',
  '    open "https://nodejs.org/en/download" 2>/dev/null || xdg-open "https://nodejs.org/en/download"',
  "    read -r; exit 1",
  "  fi",
  "fi",
  "",
  'echo "  [1 de 2] Baixando os componentes do agente..."',
  "npm install || { echo; echo \"  Algo deu errado. Mande um print para o suporte.\"; read -r; exit 1; }",
  "echo",
  'echo "  [2 de 2] Instalando o navegador que o agente usa..."',
  "npx --yes playwright install chromium || { echo; echo \"  Algo deu errado. Mande um print para o suporte.\"; read -r; exit 1; }",
  "",
  "echo",
  'echo "  ============================================"',
  'echo "    PRONTO! Agora feche esta janela e abra"',
  'echo "    o LIGAR-AGENTE.command"',
  'echo "  ============================================"',
  "echo",
  'read -r -p "  Aperte Enter para fechar."',
  "",
].join("\n");

export const LIGAR_COMMAND = [
  "#!/bin/bash",
  'cd "$(dirname "$0")/agente" || { echo "Nao encontrei a pasta agente."; read -r; exit 1; }',
  "",
  "if ! command -v node >/dev/null 2>&1 || [ ! -d node_modules ]; then",
  '  echo "  Ainda falta instalar. Abra o INSTALAR-AGENTE.command primeiro."',
  "  read -r; exit 1",
  "fi",
  "",
  "echo",
  'echo "  ============================================"',
  'echo "    AGENTE LIGADO"',
  "echo",
  'echo "    NAO FECHE esta janela enquanto estiver"',
  'echo "    usando a prospeccao."',
  'echo "  ============================================"',
  "echo",
  "npm run servico",
  "echo",
  'read -r -p "  O agente parou. Aperte Enter para fechar."',
  "",
].join("\n");
